### ISSUE TITLE
Inexplicably cannot deploy if there is no currently deployed app!

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/roku-deploy#64]
If no app is currently side-loaded, then we get:  

```
  Error: Delete Failed: No such file or directory.
      at new FailedDeviceResponseError (node_modules/roku-deploy/dist/Errors.js:52:28)
      at RokuDeploy.checkRequest (node_modules/roku-deploy/dist/RokuDeploy.js:873:19)
      at RokuDeploy.<anonymous> (node_modules/roku-deploy/dist/RokuDeploy.js:830:34)
      at step (node_modules/roku-deploy/dist/RokuDeploy.js:44:23)
      at Object.next (node_modules/roku-deploy/dist/RokuDeploy.js:25:53)
      at fulfilled (node_modules/roku-deploy/dist/RokuDeploy.js:16:58)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)

```

this is coz the HTTP delete fails - that error should be ignored.
If I get a mo, I'll put a pr up; but it's unlikely

**Comment by TwitchBronBron** [comment]
Resolved by #65
